### ISSUE TITLE
A few question

### ISSUE THREAD

**Issue by paladin-t** [untoxa/gbvm#1]
Hi @untoxa,

Thank you for making GBVM, it's a great project. I got a few questions, hope I'm putting it at the right place.

I noticed that there are two major branches you've committed to - https://github.com/untoxa/gbvm/ and https://github.com/chrismaltby/gbvm, so my first question is how do they get supported respectively? Could I suppose that /untoxa/gbvm is a purer version with core features, /chrismaltby/gbvm is enhanced with a number of advanced functions for GB Studio, however they both will get long term support and maintenance.

I'm currently working on a custom engine based on GBVM, what I need is a purer version, but I also need advanced sprite, map, etc functions. So my main question is, would you recommend to use /untoxa/gbvm or /chrismaltby/gbvm? I wish to stick around with a well maintained version for furture updates.

One more question, is there any plan to support fixed-point real number?

Thanks.

**Comment by untoxa** [comment]
This repo is a pure GBVM project, that contains the engine only. It is not bound to any project, it can even be the base for not the game, but something very different, like some language interpreter. It is also cross-platform.

https://github.com/chrismaltby/gbvm is a fork of this base project that is actually the whole GBStudio https://www.gbstudio.dev/ core - part that runs on the game boy. Not just GBVM. GBVM itself is like 30% there, and you can't "put it out", because it is customized for the GBStudio needs.

So. If you want to create something new from scratch, you should better fork this repo. If you want something more or less complete, then i suggest you to use GBStudio itesef - you can make all the art and level design in the GBStudio, then just use "Eject engine" feature and then edit the engine. 

Probably, for the "custom engine based on GBVM" GBStudio fork is too specific. 

Fixed point real numbers are just scaled integers. You may just use VM_RPN to shift numbers by 4 back and forth to get (1/16 fraction), or multiply/divide by 100, if you prefer decimals, but that is much slower than shifting.

**Comment by paladin-t** [comment]
thanks for the reply, it’s fair clear. keep up the great work!
